# MPLAB IDE generated this makefile for use with GNU make.
# Project: uygulama-16.mcp
# Date: Sat Oct 20 20:59:58 2018

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

uygulama-16.cof : uygulama-16.o
	$(CC) /p16F877A "uygulama-16.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"uygulama-16.cof" /M"uygulama-16.map" /W

uygulama-16.o : uygulama-16.asm C:/Program\ Files\ (x86)/Microchip/MPASM\ Suite/P16F877A.INC
	$(AS) /q /p16F877A "uygulama-16.asm" /l"uygulama-16.lst" /e"uygulama-16.err" /o"uygulama-16.o" /d__DEBUG=1

clean : 
	$(CC) "uygulama-16.o" "uygulama-16.err" "uygulama-16.lst" "uygulama-16.cof" "uygulama-16.hex"

