# MPLAB IDE generated this makefile for use with GNU make.
# Project: uygulama-11.mcp
# Date: Sun Oct 14 18:26:13 2018

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

uygulama-11.cof : uygulama-11.o
	$(CC) /p16F877A "uygulama-11.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"uygulama-11.cof" /M"uygulama-11.map" /W /x

uygulama-11.o : uygulama-11.asm C:/Program\ Files\ (x86)/Microchip/MPASM\ Suite/P16F877A.INC
	$(AS) /q /p16F877A "uygulama-11.asm" /l"uygulama-11.lst" /e"uygulama-11.err" /d__DEBUG=1

clean : 
	$(CC) "uygulama-11.o" "uygulama-11.hex" "uygulama-11.err" "uygulama-11.lst" "uygulama-11.cof"

