# MPLAB IDE generated this makefile for use with GNU make.
# Project: uygulama-13.mcp
# Date: Sat Oct 20 18:12:37 2018

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

uygulama-13.cof : uygulama-13.o
	$(CC) /p16F877A "uygulama-13.o" /z__MPLAB_BUILD=1 /o"uygulama-13.cof" /M"uygulama-13.map" /W /x

uygulama-13.o : uygulama-13.asm C:/Program\ Files\ (x86)/Microchip/MPASM\ Suite/P16F877A.INC
	$(AS) /q /p16F877A "uygulama-13.asm" /l"uygulama-13.lst" /e"uygulama-13.err"

clean : 
	$(CC) "uygulama-13.o" "uygulama-13.hex" "uygulama-13.err" "uygulama-13.lst" "uygulama-13.cof"

