	LIST P=16F877A
	#INCLUDE <P16F877A.INC>
	ORG 0X00
	GOTO ANA_METOT
	
ANA_METOT
	BANKSEL TRISB
	MOVLW B'11111111'	;B PORTU GÝRÝÞ OLARAK AYARLANDI.
	MOVWF TRISB
	MOVLW B'00000000'	;C PORTU ÇIKIÞ OLARAK AYARLANDI.
	MOVWF TRISC
	BANKSEL PORTB
	BSF PORTB,0
	BCF PORTC,0
	
KONTROL
	BTFSS PORTB,0		;B PORTUNUN 0.BACAÐI KONTROL EDÝLDÝ. BACAÐA BASMA DURUMU 1; BASMAMA DURUMU 0 OLARAK AYARLANDI.
	GOTO LED_SON
	GOTO LED_YAK

LED_YAK
	BSF PORTC,0		;C PORTUNUN 0.BACAÐINI YAKMA DURUMU
	GOTO KONTROL

LED_SON
	BCF PORTC,0		;C PORTUNUN 0.BACAÐINI SÖNDÜRME DURUMU
	GOTO KONTROL

END