# MPLAB IDE generated this makefile for use with GNU make.
# Project: uygulama-7.mcp
# Date: Mon Oct 08 16:06:03 2018

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

uygulama-7.cof : uygulama-7.o
	$(CC) /p16F877A "uygulama-7.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"uygulama-7.cof" /M"uygulama-7.map" /W /x

uygulama-7.o : uygulama-7.asm C:/Program\ Files\ (x86)/Microchip/MPASM\ Suite/P16F877A.INC
	$(AS) /q /p16F877A "uygulama-7.asm" /l"uygulama-7.lst" /e"uygulama-7.err" /d__DEBUG=1

clean : 
	$(CC) "uygulama-7.o" "uygulama-7.hex" "uygulama-7.err" "uygulama-7.lst" "uygulama-7.cof"

