# MPLAB IDE generated this makefile for use with GNU make.
# Project: uygulama-6.mcp
# Date: Sun Oct 07 18:54:23 2018

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

uygulama-6.cof : uygulama-6.o
	$(CC) /p16F877A "uygulama-6.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"uygulama-6.cof" /M"uygulama-6.map" /W /x

uygulama-6.o : uygulama-6.asm C:/Program\ Files\ (x86)/Microchip/MPASM\ Suite/P16F877A.INC
	$(AS) /q /p16F877A "uygulama-6.asm" /l"uygulama-6.lst" /e"uygulama-6.err" /d__DEBUG=1

clean : 
	$(CC) "uygulama-6.o" "uygulama-6.hex" "uygulama-6.err" "uygulama-6.lst" "uygulama-6.cof"

